# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import transmission_call_pb2 as transmission__call__pb2


class TransmissionCallStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetTorrent = channel.unary_unary(
        '/TransmissionCall/GetTorrent',
        request_serializer=transmission__call__pb2.TorrentId.SerializeToString,
        response_deserializer=transmission__call__pb2.getTorrent.FromString,
        )
    self.SendTorrent = channel.unary_unary(
        '/TransmissionCall/SendTorrent',
        request_serializer=transmission__call__pb2.TorrentUrl.SerializeToString,
        response_deserializer=transmission__call__pb2.sendTorrent.FromString,
        )


class TransmissionCallServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetTorrent(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SendTorrent(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TransmissionCallServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetTorrent': grpc.unary_unary_rpc_method_handler(
          servicer.GetTorrent,
          request_deserializer=transmission__call__pb2.TorrentId.FromString,
          response_serializer=transmission__call__pb2.getTorrent.SerializeToString,
      ),
      'SendTorrent': grpc.unary_unary_rpc_method_handler(
          servicer.SendTorrent,
          request_deserializer=transmission__call__pb2.TorrentUrl.FromString,
          response_serializer=transmission__call__pb2.sendTorrent.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'TransmissionCall', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
